server:
  port: 80

spring:
  main:
    allow-circular-references: true #循环错误 ？
  mvc:
    pathmatch:
      matching-strategy: PATH_PATTERN_PARSER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus?serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: root
    ##配置druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5  #初始化后的连接数
      minIdle: 5   #最小连接池的数量
      max-active: 20  #最大连接池数量
      max-wait: 60000 #获取连接时最大等待时间
      time-between-eviction-runs-millis: 60000  #连接的间隔时间
      min-evictable-idle-time-millis: 3000000 #连接保持空闲⽽而不不被驱逐的最⻓长时间
      validation-query: SELECT 1 FROM DUAL  #用来检测连接是否有效的sql，要求是一个查询语句
      test-while-idle: true #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-on-borrow: false #true：申请连接时执行validationQuery检测连接是否有效，影响性能
      test-on-return: false #true：归还连接时执行validationQuery检测连接是否有效
      pool-prepared-statements: true  #打开PSCache
      #配置监控统计拦截的filter；stat：监控统计，log4j：日志记录，wall：防御sql注入
      filters: stat,wall,log4j,config
      max-pool-prepared-statement-per-connection-size: 20 #指定每个连接上PSCache的大小
      use-global-data-source-stat: true #合并多个DruidDatSource的监控数据
      # 打开mergeSql（合并sql）功能
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000








mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #console显示sql语句

jwt:
  #过期时间：2小时
  expire: 7200000
  #密钥
  secret: secret99


